name: build project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildjob1:
    runs-on: ubuntu-latest
    steps:
    - name: buildstep1
      uses: actions/checkout@v4
  buildjobs2:
    runs-on: macos-latest    
    steps:  
    - name: buildstep2
      uses: actions/checkout@v4
  buildjobs3:
    runs-on: windows-latest
    steps:
    - name: buildstep3
      run: echo When the class will get compelted
